# Generated by Django 6.1.1 on 2026-09-24 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persons', '0001_initial'),
        ('users', '0002_remove_usuario_roles_usuariorol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Festivo',
            fields=[
                ('id', models.AutoField(db_column='fes_id', primary_key=True, serialize=False)),
                ('fecha', models.DateField(db_column='fes_fecha', unique=True)),
                ('descripcion', models.CharField(blank=True, db_column='fes_descripcion', max_length=100, null=True)),
            ],
            options={
                'db_table': 'festivo',
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.AutoField(db_column='cita_id', primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(db_column='fecha_hora_cita')),
                ('estado', models.CharField(choices=[('PROGRAMADA', 'Programada'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('ATENDIDA', 'Atendida'), ('NO_ASISTIDA', 'No asistida')], db_column='cita_estado', default='PROGRAMADA', max_length=30)),
                ('observacion', models.CharField(blank=True, db_column='observacion', max_length=500, null=True)),
                ('medico', models.ForeignKey(db_column='medico_id', on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='persons.medico')),
                ('paciente', models.ForeignKey(db_column='paciente_id', on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='persons.paciente')),
                ('usuario', models.ForeignKey(db_column='usu_id', on_delete=django.db.models.deletion.PROTECT, related_name='citas_creadas', to='users.usuario')),
            ],
            options={
                'db_table': 'cita',
            },
        ),
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.AutoField(db_column='hc_id', primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(db_column='hc_fecha_hora')),
                ('descripcion', models.CharField(db_column='hc_descripcion', max_length=500)),
                ('cita', models.OneToOneField(db_column='cita_id', on_delete=django.db.models.deletion.PROTECT, related_name='historia_clinica', to='appointments.cita')),
            ],
            options={
                'db_table': 'historiaclinica',
            },
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['paciente'], name='idx_cita_paciente'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['fecha_hora'], name='idx_cita_fecha'),
        ),
        migrations.AddConstraint(
            model_name='cita',
            constraint=models.UniqueConstraint(fields=('medico', 'fecha_hora'), name='uq_cita_medico_fecha_hora'),
        ),
    ]
