# Generated by Django 6.1.1 on 2026-09-23 22:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id', models.AutoField(db_column='disp_id', primary_key=True, serialize=False)),
                ('dia_semana', models.CharField(choices=[('LUNES', 'Lunes'), ('MARTES', 'Martes'), ('MIERCOLES', 'Miércoles'), ('JUEVES', 'Jueves'), ('VIERNES', 'Viernes')], db_column='disp_dia_semana', max_length=20)),
                ('hora_inicio', models.TimeField(db_column='disp_hora_inicio')),
                ('hora_fin', models.TimeField(db_column='disp_hora_fin')),
                ('intervalo', models.PositiveIntegerField(db_column='disp_intervalo', validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'db_table': 'disponibilidad',
            },
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.AutoField(db_column='esp_id', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='esp_nombre', max_length=50, unique=True)),
            ],
            options={
                'db_table': 'especialidad',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(db_column='per_id', primary_key=True, serialize=False)),
                ('primer_nombre', models.CharField(db_column='per_primer_nombre', max_length=50)),
                ('segundo_nombre', models.CharField(blank=True, db_column='per_segundo_nombre', max_length=50, null=True)),
                ('primer_apellido', models.CharField(db_column='per_primer_apellido', max_length=50)),
                ('segundo_apellido', models.CharField(blank=True, db_column='per_segundo_apellido', max_length=50, null=True)),
                ('genero', models.CharField(choices=[('HOMBRE', 'Hombre'), ('MUJER', 'Mujer'), ('OTRO', 'Otro')], db_column='per_genero', max_length=10)),
                ('fecha_nacimiento', models.DateField(db_column='per_fecha_nac')),
                ('telefono', models.CharField(db_column='per_telefono', max_length=15)),
                ('dni', models.IntegerField(db_column='per_dni', unique=True)),
                ('correo', models.EmailField(blank=True, db_column='per_correo', max_length=70, null=True)),
            ],
            options={
                'db_table': 'persona',
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('persona', models.OneToOneField(db_column='per_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='medico', serialize=False, to='persons.persona')),
                ('tipo_profesional', models.CharField(choices=[('MEDICO', 'Médico'), ('TERAPISTA', 'Terapista')], db_column='med_tipo_profesional', max_length=20)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], db_column='med_estado', default='ACTIVO', max_length=20)),
            ],
            options={
                'db_table': 'medico',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('persona', models.OneToOneField(db_column='per_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='paciente', serialize=False, to='persons.persona')),
            ],
            options={
                'db_table': 'paciente',
            },
        ),
        migrations.CreateModel(
            name='MedicoEspecialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.ForeignKey(db_column='esp_id', on_delete=django.db.models.deletion.CASCADE, related_name='medicos', to='persons.especialidad')),
                ('medico', models.ForeignKey(db_column='per_id', on_delete=django.db.models.deletion.CASCADE, related_name='especialidades', to='persons.medico')),
            ],
            options={
                'db_table': 'medicoespecialidad',
                'constraints': [models.UniqueConstraint(fields=('medico', 'especialidad'), name='pk_medicoespecialidad')],
            },
        ),
        migrations.CreateModel(
            name='MedicoDisponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disponibilidad', models.ForeignKey(db_column='disp_id', on_delete=django.db.models.deletion.CASCADE, related_name='medicos', to='persons.disponibilidad')),
                ('medico', models.ForeignKey(db_column='per_id', on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='persons.medico')),
            ],
            options={
                'db_table': 'medicodisponibilidad',
                'constraints': [models.UniqueConstraint(fields=('medico', 'disponibilidad'), name='pk_medicodisponibilidad')],
            },
        ),
    ]
