# Generated by Django 6.1.1 on 2026-09-23 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(db_column='rol_id', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='rol_nombre', max_length=50, unique=True)),
            ],
            options={
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(db_column='usu_id', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='username', max_length=20, unique=True)),
                ('keycloak_user_id', models.CharField(blank=True, db_column='keycloak_user_id', max_length=100, null=True, unique=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], db_column='usu_estado', default='ACTIVO', max_length=20)),
                ('persona', models.OneToOneField(blank=True, db_column='per_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario', to='persons.persona')),
                ('roles', models.ManyToManyField(db_table='usuariorol', related_name='usuarios', to='users.rol')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    ]
