# Generated by Django 6.1.1 on 2026-09-23 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='roles',
        ),
        migrations.CreateModel(
            name='UsuarioRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.ForeignKey(db_column='rol_id', on_delete=django.db.models.deletion.CASCADE, related_name='relaciones_usuario', to='users.rol')),
                ('usuario', models.ForeignKey(db_column='usu_id', on_delete=django.db.models.deletion.CASCADE, related_name='relaciones_rol', to='users.usuario')),
            ],
            options={
                'db_table': 'usuariorol',
                'constraints': [models.UniqueConstraint(fields=('usuario', 'rol'), name='pk_usuariorol')],
            },
        ),
    ]
